version: '3'
services:
    server:
        image: purvesta/cs455-p3:latest
        networks:
            backend:
        ports:
        - "1099"
networks:
    backend:
        ipam:
            config:
            - subnet: 172.20.0.0/24
